# Generated by Django 5.1.2 on 2024-11-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=255)),
                ('rate', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
